name: realtime_location_tracker
description: Real-time location tracking application with WebSocket, cross-platform support (Android, iOS, Windows, macOS, Web) using Flutter and open-source maps.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  web_socket_channel: ^3.0.3
  http: ^1.2.0

  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  maplibre_gl: ^0.24.1

  provider: ^6.1.2

  uuid: ^4.3.3
  intl: ^0.20.2

  flutter_animate: ^4.5.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
    
  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
